### ISSUE TITLE
Create Factorio mod portal meta information

### ISSUE THREAD

**Issue by alifeee** [alifeee/Factorio-Proximity-Voice-Chat#3]
Create:

- [x] file for description (markdown)
- [x] file for image
- [x] change info.json

![image](https://github.com/alifeee/Factorio-Proximity-Voice-Chat/assets/13833017/68089084-532d-41ee-b1e6-19dc5920b2e0)

**Comment by alifeee** [comment]
done in release 0.6.0
